### ISSUE TITLE
/metrics returns 404

### ISSUE THREAD

**Issue by stanislavromanov** [miekg/caddy-prometheus#20]
Even when I enable the prometheus and I have prometheus extension it returns me 404 when I go to `/metrics` url. Am I doing something wrong?

Here is my Caddyfile
```
mydomain.com {
        prometheus
        root /var/www/lab3
}
```

**Comment by herohamp** [comment]
How did you fix this?

**Comment by hairyhenderson** [comment]
@herohamp if you're having an issue it's probably best to open a new one instead of commenting on an issue that closed almost 2 years ago 😉

That being said, it's worth remembering that the `/metrics` endpoint is served on a different address than the site itself. See https://github.com/miekg/caddy-prometheus#use for details.

**Comment by herohamp** [comment]
Yeah that probably would have been the smart thing to do ;P I ended up figuring it out
