### ISSUE TITLE
"Family" label doesn't work

### ISSUE THREAD

**Issue by calmh** [miekg/caddy-prometheus#38]
It always gets set to "1" regardless of whether the request is over IPv4 or IPv6.

**Comment by genofire** [comment]
Label should be "4" and "6" and not "1" and "2" ...

**Comment by miekg** [comment]
Why?

On 10 Oct 2018 10:59, "Geno" <notifications@github.com> wrote:

Label should be "4" and "6" and not "1" and "2" ...

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/miekg/caddy-prometheus/issues/38#issuecomment-428512923>,
or mute the thread
